#!/bin/sh

goto_config()
{
 cd /config;
}


install_etc()
{
 echo "Install /config/etc to /etc";

 goto_config

 for i in `find etc -type f |grep -v "\.skip"`; do
  echo Link /config/$i to /$i
  if [[ ! -e /$i ]]; then
   ln -s /config/$i /$i
   echo "Installed."
  else 
   echo "File exists, skipping..."
  fi
  echo ""
 done;

}


install_etc


