#!/bin/bash

for i in $(ls /config/ipset-list/*.list); do
 echo $i;
 ipset_name=$(basename $i .list)

 while read ip; do
     if ! [[ $ip =~ ^# ]]; then
   /sbin/ipset -! add $ipset_name $ip;
     fi;
 done < $i

done
